export const ADD_BOARD = "ADD_BOARD";
export const GET_ALL_AGENCIES_SUCCESS = "GET_ALL_AGENCIES_SUCCESS";
export const GET_ALL_CSRS_SUCCESS = "GET_ALL_CSRS_SUCCESS";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
